sudo: required

env:
- GHCVER=8.0.2
- GHCVER=8.2.2
- GHCVER=8.4.4
- GHCVER=8.6.5
- GHCVER=8.8.3
- GHCVER=8.10.1
- GHCVER=head

script:
- curl -sSL https://raw.github.com/tomjaguarpaw/neil/d960b6a/travis.sh | sh -s tomjaguarpaw d960b6a
